name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          persist-credentials: false

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake make libdbus-1-dev libevent-dev

      - name: Build
        run: |
          cmake -S ./tests -B build -DENABLE_COVERAGE=ON
          cmake --build build

      - name: Run tests and generate JUnit XML
        run: |
          mkdir -p test-results
          cd build
          ./dbus-canopen-motordrive-test "--gtest_output=xml:../test-results/results.xml"

      - name: Report test results
        uses: dorny/test-reporter@v2
        if: always()   # ensure results are shown even if tests fail
        with:
          name: GoogleTest Results
          path: test-results/results.xml
          reporter: java-junit
